// Copyright (c) 2026 SLTV authors. Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/sltv.proto

// Package sltv.v1 is the public gRPC API exposed by the sltvd daemon
// (Shared Logical Thin Volume). Clients such as sctl talk to sltvd
// through this service.

package sltvv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sltv_CreateDisk_FullMethodName       = "/sltv.v1.Sltv/CreateDisk"
	Sltv_DeleteDisk_FullMethodName       = "/sltv.v1.Sltv/DeleteDisk"
	Sltv_GetDisk_FullMethodName          = "/sltv.v1.Sltv/GetDisk"
	Sltv_ListDisks_FullMethodName        = "/sltv.v1.Sltv/ListDisks"
	Sltv_ExtendDisk_FullMethodName       = "/sltv.v1.Sltv/ExtendDisk"
	Sltv_AttachDisk_FullMethodName       = "/sltv.v1.Sltv/AttachDisk"
	Sltv_DetachDisk_FullMethodName       = "/sltv.v1.Sltv/DetachDisk"
	Sltv_ListAttachments_FullMethodName  = "/sltv.v1.Sltv/ListAttachments"
	Sltv_GetNodeStatus_FullMethodName    = "/sltv.v1.Sltv/GetNodeStatus"
	Sltv_GetClusterStatus_FullMethodName = "/sltv.v1.Sltv/GetClusterStatus"
)

// SltvClient is the client API for Sltv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sltv is the daemon-side service exposed over gRPC.
type SltvClient interface {
	// CreateDisk provisions a new logical volume (and qcow2 image when
	// thin-provisioned) and registers it in the catalog.
	CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*Disk, error)
	// DeleteDisk removes the LV after ensuring no attachments remain.
	DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetDisk returns metadata about a single disk.
	GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*Disk, error)
	// ListDisks returns all known disks, optionally filtered by VG.
	ListDisks(ctx context.Context, in *ListDisksRequest, opts ...grpc.CallOption) (*ListDisksResponse, error)
	// ExtendDisk manually grows the backing LV (and notifies QEMU).
	ExtendDisk(ctx context.Context, in *ExtendDiskRequest, opts ...grpc.CallOption) (*Disk, error)
	// AttachDisk hot-plugs the disk into a libvirt domain (PERSISTENT|LIVE).
	AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*Attachment, error)
	// DetachDisk removes the disk from a libvirt domain.
	DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListAttachments returns matching attachments.
	ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error)
	// GetNodeStatus reports the local node's view.
	GetNodeStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	// GetClusterStatus reports cluster-wide state when clustering is enabled.
	GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterStatus, error)
}

type sltvClient struct {
	cc grpc.ClientConnInterface
}

func NewSltvClient(cc grpc.ClientConnInterface) SltvClient {
	return &sltvClient{cc}
}

func (c *sltvClient) CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*Disk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Disk)
	err := c.cc.Invoke(ctx, Sltv_CreateDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Sltv_DeleteDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*Disk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Disk)
	err := c.cc.Invoke(ctx, Sltv_GetDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) ListDisks(ctx context.Context, in *ListDisksRequest, opts ...grpc.CallOption) (*ListDisksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDisksResponse)
	err := c.cc.Invoke(ctx, Sltv_ListDisks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) ExtendDisk(ctx context.Context, in *ExtendDiskRequest, opts ...grpc.CallOption) (*Disk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Disk)
	err := c.cc.Invoke(ctx, Sltv_ExtendDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, Sltv_AttachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Sltv_DetachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttachmentsResponse)
	err := c.cc.Invoke(ctx, Sltv_ListAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) GetNodeStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, Sltv_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sltvClient) GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, Sltv_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SltvServer is the server API for Sltv service.
// All implementations must embed UnimplementedSltvServer
// for forward compatibility.
//
// Sltv is the daemon-side service exposed over gRPC.
type SltvServer interface {
	// CreateDisk provisions a new logical volume (and qcow2 image when
	// thin-provisioned) and registers it in the catalog.
	CreateDisk(context.Context, *CreateDiskRequest) (*Disk, error)
	// DeleteDisk removes the LV after ensuring no attachments remain.
	DeleteDisk(context.Context, *DeleteDiskRequest) (*emptypb.Empty, error)
	// GetDisk returns metadata about a single disk.
	GetDisk(context.Context, *GetDiskRequest) (*Disk, error)
	// ListDisks returns all known disks, optionally filtered by VG.
	ListDisks(context.Context, *ListDisksRequest) (*ListDisksResponse, error)
	// ExtendDisk manually grows the backing LV (and notifies QEMU).
	ExtendDisk(context.Context, *ExtendDiskRequest) (*Disk, error)
	// AttachDisk hot-plugs the disk into a libvirt domain (PERSISTENT|LIVE).
	AttachDisk(context.Context, *AttachDiskRequest) (*Attachment, error)
	// DetachDisk removes the disk from a libvirt domain.
	DetachDisk(context.Context, *DetachDiskRequest) (*emptypb.Empty, error)
	// ListAttachments returns matching attachments.
	ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error)
	// GetNodeStatus reports the local node's view.
	GetNodeStatus(context.Context, *emptypb.Empty) (*NodeStatus, error)
	// GetClusterStatus reports cluster-wide state when clustering is enabled.
	GetClusterStatus(context.Context, *emptypb.Empty) (*ClusterStatus, error)
	mustEmbedUnimplementedSltvServer()
}

// UnimplementedSltvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSltvServer struct{}

func (UnimplementedSltvServer) CreateDisk(context.Context, *CreateDiskRequest) (*Disk, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDisk not implemented")
}
func (UnimplementedSltvServer) DeleteDisk(context.Context, *DeleteDiskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDisk not implemented")
}
func (UnimplementedSltvServer) GetDisk(context.Context, *GetDiskRequest) (*Disk, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisk not implemented")
}
func (UnimplementedSltvServer) ListDisks(context.Context, *ListDisksRequest) (*ListDisksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDisks not implemented")
}
func (UnimplementedSltvServer) ExtendDisk(context.Context, *ExtendDiskRequest) (*Disk, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendDisk not implemented")
}
func (UnimplementedSltvServer) AttachDisk(context.Context, *AttachDiskRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDisk not implemented")
}
func (UnimplementedSltvServer) DetachDisk(context.Context, *DetachDiskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachDisk not implemented")
}
func (UnimplementedSltvServer) ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttachments not implemented")
}
func (UnimplementedSltvServer) GetNodeStatus(context.Context, *emptypb.Empty) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedSltvServer) GetClusterStatus(context.Context, *emptypb.Empty) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedSltvServer) mustEmbedUnimplementedSltvServer() {}
func (UnimplementedSltvServer) testEmbeddedByValue()              {}

// UnsafeSltvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SltvServer will
// result in compilation errors.
type UnsafeSltvServer interface {
	mustEmbedUnimplementedSltvServer()
}

func RegisterSltvServer(s grpc.ServiceRegistrar, srv SltvServer) {
	// If the following call panics, it indicates UnimplementedSltvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sltv_ServiceDesc, srv)
}

func _Sltv_CreateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).CreateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_CreateDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).CreateDisk(ctx, req.(*CreateDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_DeleteDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).DeleteDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_DeleteDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).DeleteDisk(ctx, req.(*DeleteDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_GetDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).GetDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_GetDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).GetDisk(ctx, req.(*GetDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_ListDisks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDisksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).ListDisks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_ListDisks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).ListDisks(ctx, req.(*ListDisksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_ExtendDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).ExtendDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_ExtendDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).ExtendDisk(ctx, req.(*ExtendDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_AttachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).AttachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_AttachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).AttachDisk(ctx, req.(*AttachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_DetachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).DetachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_DetachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).DetachDisk(ctx, req.(*DetachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_ListAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).ListAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_ListAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).ListAttachments(ctx, req.(*ListAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).GetNodeStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sltv_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SltvServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sltv_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SltvServer).GetClusterStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Sltv_ServiceDesc is the grpc.ServiceDesc for Sltv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sltv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sltv.v1.Sltv",
	HandlerType: (*SltvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDisk",
			Handler:    _Sltv_CreateDisk_Handler,
		},
		{
			MethodName: "DeleteDisk",
			Handler:    _Sltv_DeleteDisk_Handler,
		},
		{
			MethodName: "GetDisk",
			Handler:    _Sltv_GetDisk_Handler,
		},
		{
			MethodName: "ListDisks",
			Handler:    _Sltv_ListDisks_Handler,
		},
		{
			MethodName: "ExtendDisk",
			Handler:    _Sltv_ExtendDisk_Handler,
		},
		{
			MethodName: "AttachDisk",
			Handler:    _Sltv_AttachDisk_Handler,
		},
		{
			MethodName: "DetachDisk",
			Handler:    _Sltv_DetachDisk_Handler,
		},
		{
			MethodName: "ListAttachments",
			Handler:    _Sltv_ListAttachments_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _Sltv_GetNodeStatus_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _Sltv_GetClusterStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/sltv.proto",
}
