// Copyright (c) 2026 SLTV authors. Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/sltv.proto

// Package sltv.v1 is the public gRPC API exposed by the sltvd daemon
// (Shared Logical Thin Volume). Clients such as sctl talk to sltvd
// through this service.

package sltvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProvisionMode indicates whether a disk is fully allocated up-front
// (THICK) or grows on demand by extending its backing logical volume
// (THIN).
type ProvisionMode int32

const (
	ProvisionMode_PROVISION_MODE_UNSPECIFIED ProvisionMode = 0
	ProvisionMode_PROVISION_MODE_THICK       ProvisionMode = 1
	ProvisionMode_PROVISION_MODE_THIN        ProvisionMode = 2
)

// Enum value maps for ProvisionMode.
var (
	ProvisionMode_name = map[int32]string{
		0: "PROVISION_MODE_UNSPECIFIED",
		1: "PROVISION_MODE_THICK",
		2: "PROVISION_MODE_THIN",
	}
	ProvisionMode_value = map[string]int32{
		"PROVISION_MODE_UNSPECIFIED": 0,
		"PROVISION_MODE_THICK":       1,
		"PROVISION_MODE_THIN":        2,
	}
)

func (x ProvisionMode) Enum() *ProvisionMode {
	p := new(ProvisionMode)
	*p = x
	return p
}

func (x ProvisionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sltv_proto_enumTypes[0].Descriptor()
}

func (ProvisionMode) Type() protoreflect.EnumType {
	return &file_v1_sltv_proto_enumTypes[0]
}

func (x ProvisionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionMode.Descriptor instead.
func (ProvisionMode) EnumDescriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{0}
}

// Disk represents a single LVM-backed disk managed by sltvd.
type Disk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique disk name (also the LV name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Volume group the LV lives in.
	Vg string `protobuf:"bytes,2,opt,name=vg,proto3" json:"vg,omitempty"`
	// Provisioning mode.
	Mode ProvisionMode `protobuf:"varint,3,opt,name=mode,proto3,enum=sltv.v1.ProvisionMode" json:"mode,omitempty"`
	// Physical size of the backing LV in bytes.
	SizeBytes uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Virtual (guest-visible) size in bytes. Equals size_bytes for THICK.
	VirtualSizeBytes uint64 `protobuf:"varint,5,opt,name=virtual_size_bytes,json=virtualSizeBytes,proto3" json:"virtual_size_bytes,omitempty"`
	// Path to the backing block device, e.g. /dev/vg-sltv/web01-data.
	DevicePath string `protobuf:"bytes,6,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	// Node that initially created the disk (informational).
	CreatedOnNode string `protobuf:"bytes,7,opt,name=created_on_node,json=createdOnNode,proto3" json:"created_on_node,omitempty"`
	// Creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last extend timestamp (THIN only). Zero if never extended.
	LastExtendedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_extended_at,json=lastExtendedAt,proto3" json:"last_extended_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_v1_sltv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{0}
}

func (x *Disk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disk) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

func (x *Disk) GetMode() ProvisionMode {
	if x != nil {
		return x.Mode
	}
	return ProvisionMode_PROVISION_MODE_UNSPECIFIED
}

func (x *Disk) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Disk) GetVirtualSizeBytes() uint64 {
	if x != nil {
		return x.VirtualSizeBytes
	}
	return 0
}

func (x *Disk) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *Disk) GetCreatedOnNode() string {
	if x != nil {
		return x.CreatedOnNode
	}
	return ""
}

func (x *Disk) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Disk) GetLastExtendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastExtendedAt
	}
	return nil
}

// Attachment describes a disk attached to a libvirt domain on a host.
type Attachment struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DiskName string                 `protobuf:"bytes,1,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	VmName   string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	// Host (sltvd node) where the libvirt domain runs.
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// Target device inside the guest, e.g. "vdb".
	TargetDev string `protobuf:"bytes,4,opt,name=target_dev,json=targetDev,proto3" json:"target_dev,omitempty"`
	// Attachment timestamp.
	AttachedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=attached_at,json=attachedAt,proto3" json:"attached_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_v1_sltv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *Attachment) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *Attachment) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Attachment) GetTargetDev() string {
	if x != nil {
		return x.TargetDev
	}
	return ""
}

func (x *Attachment) GetAttachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttachedAt
	}
	return nil
}

// NodeStatus is reported by the local sltvd instance.
type NodeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ClusterEnabled bool                   `protobuf:"varint,3,opt,name=cluster_enabled,json=clusterEnabled,proto3" json:"cluster_enabled,omitempty"`
	// Volume groups visible on this node.
	Vgs           []*VolumeGroup `protobuf:"bytes,4,rep,name=vgs,proto3" json:"vgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_v1_sltv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeStatus) GetClusterEnabled() bool {
	if x != nil {
		return x.ClusterEnabled
	}
	return false
}

func (x *NodeStatus) GetVgs() []*VolumeGroup {
	if x != nil {
		return x.Vgs
	}
	return nil
}

// VolumeGroup is a slimmed-down representation of LVM `vgs` output.
type VolumeGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroup) Reset() {
	*x = VolumeGroup{}
	mi := &file_v1_sltv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroup) ProtoMessage() {}

func (x *VolumeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroup.ProtoReflect.Descriptor instead.
func (*VolumeGroup) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeGroup) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VolumeGroup) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

// ClusterStatus aggregates the state of all known sltvd peers and the
// shared catalog.
type ClusterStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Leader          string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Nodes           []*NodeStatus          `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	DiskCount       uint32                 `protobuf:"varint,4,opt,name=disk_count,json=diskCount,proto3" json:"disk_count,omitempty"`
	AttachmentCount uint32                 `protobuf:"varint,5,opt,name=attachment_count,json=attachmentCount,proto3" json:"attachment_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_v1_sltv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ClusterStatus) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *ClusterStatus) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterStatus) GetDiskCount() uint32 {
	if x != nil {
		return x.DiskCount
	}
	return 0
}

func (x *ClusterStatus) GetAttachmentCount() uint32 {
	if x != nil {
		return x.AttachmentCount
	}
	return 0
}

// CreateDiskRequest is the input for Sltv.CreateDisk.
type CreateDiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional VG. When empty, the daemon's configured default_vg is used.
	Vg string `protobuf:"bytes,2,opt,name=vg,proto3" json:"vg,omitempty"`
	// Provisioning mode. Defaults to THICK if unspecified.
	Mode ProvisionMode `protobuf:"varint,3,opt,name=mode,proto3,enum=sltv.v1.ProvisionMode" json:"mode,omitempty"`
	// For THICK: the LV size in bytes. For THIN: the initial LV size in
	// bytes. May be 0 to use the configured default_initial_size.
	SizeBytes uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// For THIN: the guest-visible size in bytes. Required when mode=THIN.
	VirtualSizeBytes uint64 `protobuf:"varint,5,opt,name=virtual_size_bytes,json=virtualSizeBytes,proto3" json:"virtual_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateDiskRequest) Reset() {
	*x = CreateDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiskRequest) ProtoMessage() {}

func (x *CreateDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiskRequest.ProtoReflect.Descriptor instead.
func (*CreateDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDiskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDiskRequest) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

func (x *CreateDiskRequest) GetMode() ProvisionMode {
	if x != nil {
		return x.Mode
	}
	return ProvisionMode_PROVISION_MODE_UNSPECIFIED
}

func (x *CreateDiskRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateDiskRequest) GetVirtualSizeBytes() uint64 {
	if x != nil {
		return x.VirtualSizeBytes
	}
	return 0
}

type DeleteDiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When true, detach from any attached VMs first.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiskRequest) Reset() {
	*x = DeleteDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiskRequest) ProtoMessage() {}

func (x *DeleteDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiskRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDiskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDiskRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GetDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskRequest) Reset() {
	*x = GetDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskRequest) ProtoMessage() {}

func (x *GetDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskRequest.ProtoReflect.Descriptor instead.
func (*GetDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDisksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by volume group.
	Vg            string `protobuf:"bytes,1,opt,name=vg,proto3" json:"vg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisksRequest) Reset() {
	*x = ListDisksRequest{}
	mi := &file_v1_sltv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisksRequest) ProtoMessage() {}

func (x *ListDisksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisksRequest.ProtoReflect.Descriptor instead.
func (*ListDisksRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{8}
}

func (x *ListDisksRequest) GetVg() string {
	if x != nil {
		return x.Vg
	}
	return ""
}

type ListDisksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*Disk                `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDisksResponse) Reset() {
	*x = ListDisksResponse{}
	mi := &file_v1_sltv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDisksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDisksResponse) ProtoMessage() {}

func (x *ListDisksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDisksResponse.ProtoReflect.Descriptor instead.
func (*ListDisksResponse) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{9}
}

func (x *ListDisksResponse) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

type ExtendDiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Absolute new size in bytes; mutually exclusive with delta_bytes.
	SizeBytes uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Relative growth in bytes; mutually exclusive with size_bytes.
	DeltaBytes    uint64 `protobuf:"varint,3,opt,name=delta_bytes,json=deltaBytes,proto3" json:"delta_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendDiskRequest) Reset() {
	*x = ExtendDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendDiskRequest) ProtoMessage() {}

func (x *ExtendDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendDiskRequest.ProtoReflect.Descriptor instead.
func (*ExtendDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{10}
}

func (x *ExtendDiskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtendDiskRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ExtendDiskRequest) GetDeltaBytes() uint64 {
	if x != nil {
		return x.DeltaBytes
	}
	return 0
}

type AttachDiskRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DiskName string                 `protobuf:"bytes,1,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	VmName   string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	// Optional target device name; auto-picked when empty.
	TargetDev     string `protobuf:"bytes,3,opt,name=target_dev,json=targetDev,proto3" json:"target_dev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDiskRequest) Reset() {
	*x = AttachDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDiskRequest) ProtoMessage() {}

func (x *AttachDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDiskRequest.ProtoReflect.Descriptor instead.
func (*AttachDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{11}
}

func (x *AttachDiskRequest) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *AttachDiskRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *AttachDiskRequest) GetTargetDev() string {
	if x != nil {
		return x.TargetDev
	}
	return ""
}

type DetachDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskName      string                 `protobuf:"bytes,1,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDiskRequest) Reset() {
	*x = DetachDiskRequest{}
	mi := &file_v1_sltv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDiskRequest) ProtoMessage() {}

func (x *DetachDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDiskRequest.ProtoReflect.Descriptor instead.
func (*DetachDiskRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{12}
}

func (x *DetachDiskRequest) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *DetachDiskRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type ListAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskName      string                 `protobuf:"bytes,1,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsRequest) Reset() {
	*x = ListAttachmentsRequest{}
	mi := &file_v1_sltv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsRequest) ProtoMessage() {}

func (x *ListAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{13}
}

func (x *ListAttachmentsRequest) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *ListAttachmentsRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type ListAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attachments   []*Attachment          `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttachmentsResponse) Reset() {
	*x = ListAttachmentsResponse{}
	mi := &file_v1_sltv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttachmentsResponse) ProtoMessage() {}

func (x *ListAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sltv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_sltv_proto_rawDescGZIP(), []int{14}
}

func (x *ListAttachmentsResponse) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

var File_v1_sltv_proto protoreflect.FileDescriptor

const file_v1_sltv_proto_rawDesc = "" +
	"\n" +
	"\rv1/sltv.proto\x12\asltv.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n" +
	"\x04Disk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02vg\x18\x02 \x01(\tR\x02vg\x12*\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x16.sltv.v1.ProvisionModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12,\n" +
	"\x12virtual_size_bytes\x18\x05 \x01(\x04R\x10virtualSizeBytes\x12\x1f\n" +
	"\vdevice_path\x18\x06 \x01(\tR\n" +
	"devicePath\x12&\n" +
	"\x0fcreated_on_node\x18\a \x01(\tR\rcreatedOnNode\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x10last_extended_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0elastExtendedAt\"\xb2\x01\n" +
	"\n" +
	"Attachment\x12\x1b\n" +
	"\tdisk_name\x18\x01 \x01(\tR\bdiskName\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"target_dev\x18\x04 \x01(\tR\ttargetDev\x12;\n" +
	"\vattached_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"attachedAt\"\x90\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fcluster_enabled\x18\x03 \x01(\bR\x0eclusterEnabled\x12&\n" +
	"\x03vgs\x18\x04 \x03(\v2\x14.sltv.v1.VolumeGroupR\x03vgs\"_\n" +
	"\vVolumeGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x04R\tfreeBytes\"\xb6\x01\n" +
	"\rClusterStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\x12)\n" +
	"\x05nodes\x18\x03 \x03(\v2\x13.sltv.v1.NodeStatusR\x05nodes\x12\x1d\n" +
	"\n" +
	"disk_count\x18\x04 \x01(\rR\tdiskCount\x12)\n" +
	"\x10attachment_count\x18\x05 \x01(\rR\x0fattachmentCount\"\xb0\x01\n" +
	"\x11CreateDiskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02vg\x18\x02 \x01(\tR\x02vg\x12*\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x16.sltv.v1.ProvisionModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12,\n" +
	"\x12virtual_size_bytes\x18\x05 \x01(\x04R\x10virtualSizeBytes\"=\n" +
	"\x11DeleteDiskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"$\n" +
	"\x0eGetDiskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10ListDisksRequest\x12\x0e\n" +
	"\x02vg\x18\x01 \x01(\tR\x02vg\"8\n" +
	"\x11ListDisksResponse\x12#\n" +
	"\x05disks\x18\x01 \x03(\v2\r.sltv.v1.DiskR\x05disks\"g\n" +
	"\x11ExtendDiskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x1f\n" +
	"\vdelta_bytes\x18\x03 \x01(\x04R\n" +
	"deltaBytes\"h\n" +
	"\x11AttachDiskRequest\x12\x1b\n" +
	"\tdisk_name\x18\x01 \x01(\tR\bdiskName\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x1d\n" +
	"\n" +
	"target_dev\x18\x03 \x01(\tR\ttargetDev\"I\n" +
	"\x11DetachDiskRequest\x12\x1b\n" +
	"\tdisk_name\x18\x01 \x01(\tR\bdiskName\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\"N\n" +
	"\x16ListAttachmentsRequest\x12\x1b\n" +
	"\tdisk_name\x18\x01 \x01(\tR\bdiskName\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\"P\n" +
	"\x17ListAttachmentsResponse\x125\n" +
	"\vattachments\x18\x01 \x03(\v2\x13.sltv.v1.AttachmentR\vattachments*b\n" +
	"\rProvisionMode\x12\x1e\n" +
	"\x1aPROVISION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVISION_MODE_THICK\x10\x01\x12\x17\n" +
	"\x13PROVISION_MODE_THIN\x10\x022\x8a\x05\n" +
	"\x04Sltv\x127\n" +
	"\n" +
	"CreateDisk\x12\x1a.sltv.v1.CreateDiskRequest\x1a\r.sltv.v1.Disk\x12@\n" +
	"\n" +
	"DeleteDisk\x12\x1a.sltv.v1.DeleteDiskRequest\x1a\x16.google.protobuf.Empty\x121\n" +
	"\aGetDisk\x12\x17.sltv.v1.GetDiskRequest\x1a\r.sltv.v1.Disk\x12B\n" +
	"\tListDisks\x12\x19.sltv.v1.ListDisksRequest\x1a\x1a.sltv.v1.ListDisksResponse\x127\n" +
	"\n" +
	"ExtendDisk\x12\x1a.sltv.v1.ExtendDiskRequest\x1a\r.sltv.v1.Disk\x12=\n" +
	"\n" +
	"AttachDisk\x12\x1a.sltv.v1.AttachDiskRequest\x1a\x13.sltv.v1.Attachment\x12@\n" +
	"\n" +
	"DetachDisk\x12\x1a.sltv.v1.DetachDiskRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0fListAttachments\x12\x1f.sltv.v1.ListAttachmentsRequest\x1a .sltv.v1.ListAttachmentsResponse\x12<\n" +
	"\rGetNodeStatus\x12\x16.google.protobuf.Empty\x1a\x13.sltv.v1.NodeStatus\x12B\n" +
	"\x10GetClusterStatus\x12\x16.google.protobuf.Empty\x1a\x16.sltv.v1.ClusterStatusB\x7f\n" +
	"\vcom.sltv.v1B\tSltvProtoP\x01Z(github.com/sltv/sltv/api/proto/v1;sltvv1\xa2\x02\x03SXX\xaa\x02\aSltv.V1\xca\x02\aSltv\\V1\xe2\x02\x13Sltv\\V1\\GPBMetadata\xea\x02\bSltv::V1b\x06proto3"

var (
	file_v1_sltv_proto_rawDescOnce sync.Once
	file_v1_sltv_proto_rawDescData []byte
)

func file_v1_sltv_proto_rawDescGZIP() []byte {
	file_v1_sltv_proto_rawDescOnce.Do(func() {
		file_v1_sltv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sltv_proto_rawDesc), len(file_v1_sltv_proto_rawDesc)))
	})
	return file_v1_sltv_proto_rawDescData
}

var file_v1_sltv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_sltv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_sltv_proto_goTypes = []any{
	(ProvisionMode)(0),              // 0: sltv.v1.ProvisionMode
	(*Disk)(nil),                    // 1: sltv.v1.Disk
	(*Attachment)(nil),              // 2: sltv.v1.Attachment
	(*NodeStatus)(nil),              // 3: sltv.v1.NodeStatus
	(*VolumeGroup)(nil),             // 4: sltv.v1.VolumeGroup
	(*ClusterStatus)(nil),           // 5: sltv.v1.ClusterStatus
	(*CreateDiskRequest)(nil),       // 6: sltv.v1.CreateDiskRequest
	(*DeleteDiskRequest)(nil),       // 7: sltv.v1.DeleteDiskRequest
	(*GetDiskRequest)(nil),          // 8: sltv.v1.GetDiskRequest
	(*ListDisksRequest)(nil),        // 9: sltv.v1.ListDisksRequest
	(*ListDisksResponse)(nil),       // 10: sltv.v1.ListDisksResponse
	(*ExtendDiskRequest)(nil),       // 11: sltv.v1.ExtendDiskRequest
	(*AttachDiskRequest)(nil),       // 12: sltv.v1.AttachDiskRequest
	(*DetachDiskRequest)(nil),       // 13: sltv.v1.DetachDiskRequest
	(*ListAttachmentsRequest)(nil),  // 14: sltv.v1.ListAttachmentsRequest
	(*ListAttachmentsResponse)(nil), // 15: sltv.v1.ListAttachmentsResponse
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_v1_sltv_proto_depIdxs = []int32{
	0,  // 0: sltv.v1.Disk.mode:type_name -> sltv.v1.ProvisionMode
	16, // 1: sltv.v1.Disk.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: sltv.v1.Disk.last_extended_at:type_name -> google.protobuf.Timestamp
	16, // 3: sltv.v1.Attachment.attached_at:type_name -> google.protobuf.Timestamp
	4,  // 4: sltv.v1.NodeStatus.vgs:type_name -> sltv.v1.VolumeGroup
	3,  // 5: sltv.v1.ClusterStatus.nodes:type_name -> sltv.v1.NodeStatus
	0,  // 6: sltv.v1.CreateDiskRequest.mode:type_name -> sltv.v1.ProvisionMode
	1,  // 7: sltv.v1.ListDisksResponse.disks:type_name -> sltv.v1.Disk
	2,  // 8: sltv.v1.ListAttachmentsResponse.attachments:type_name -> sltv.v1.Attachment
	6,  // 9: sltv.v1.Sltv.CreateDisk:input_type -> sltv.v1.CreateDiskRequest
	7,  // 10: sltv.v1.Sltv.DeleteDisk:input_type -> sltv.v1.DeleteDiskRequest
	8,  // 11: sltv.v1.Sltv.GetDisk:input_type -> sltv.v1.GetDiskRequest
	9,  // 12: sltv.v1.Sltv.ListDisks:input_type -> sltv.v1.ListDisksRequest
	11, // 13: sltv.v1.Sltv.ExtendDisk:input_type -> sltv.v1.ExtendDiskRequest
	12, // 14: sltv.v1.Sltv.AttachDisk:input_type -> sltv.v1.AttachDiskRequest
	13, // 15: sltv.v1.Sltv.DetachDisk:input_type -> sltv.v1.DetachDiskRequest
	14, // 16: sltv.v1.Sltv.ListAttachments:input_type -> sltv.v1.ListAttachmentsRequest
	17, // 17: sltv.v1.Sltv.GetNodeStatus:input_type -> google.protobuf.Empty
	17, // 18: sltv.v1.Sltv.GetClusterStatus:input_type -> google.protobuf.Empty
	1,  // 19: sltv.v1.Sltv.CreateDisk:output_type -> sltv.v1.Disk
	17, // 20: sltv.v1.Sltv.DeleteDisk:output_type -> google.protobuf.Empty
	1,  // 21: sltv.v1.Sltv.GetDisk:output_type -> sltv.v1.Disk
	10, // 22: sltv.v1.Sltv.ListDisks:output_type -> sltv.v1.ListDisksResponse
	1,  // 23: sltv.v1.Sltv.ExtendDisk:output_type -> sltv.v1.Disk
	2,  // 24: sltv.v1.Sltv.AttachDisk:output_type -> sltv.v1.Attachment
	17, // 25: sltv.v1.Sltv.DetachDisk:output_type -> google.protobuf.Empty
	15, // 26: sltv.v1.Sltv.ListAttachments:output_type -> sltv.v1.ListAttachmentsResponse
	3,  // 27: sltv.v1.Sltv.GetNodeStatus:output_type -> sltv.v1.NodeStatus
	5,  // 28: sltv.v1.Sltv.GetClusterStatus:output_type -> sltv.v1.ClusterStatus
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_sltv_proto_init() }
func file_v1_sltv_proto_init() {
	if File_v1_sltv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sltv_proto_rawDesc), len(file_v1_sltv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_sltv_proto_goTypes,
		DependencyIndexes: file_v1_sltv_proto_depIdxs,
		EnumInfos:         file_v1_sltv_proto_enumTypes,
		MessageInfos:      file_v1_sltv_proto_msgTypes,
	}.Build()
	File_v1_sltv_proto = out.File
	file_v1_sltv_proto_goTypes = nil
	file_v1_sltv_proto_depIdxs = nil
}
